import { 
  Ruler, Weight, Thermometer, Square, Box, Clock, Zap, HardDrive, Coins, 
  Activity, Wind, Droplets, Sun, Moon, Map, Navigation, Compass, Globe, 
  Search, Filter, Settings, Bell, Calendar, Camera, Image, Video, Music, 
  Mic, Phone, Mail, MessageSquare, Share2, Link, Download, Upload, Cloud, 
  Lock, Shield, Key, User, Heart, Star, Flag, Bookmark, Tag, ShoppingCart, 
  CreditCard, Wallet, Briefcase, GraduationCap, Trophy, Medal, Target, 
  Rocket, Plane, Car, Bike, Truck, Ship, Anchor, Coffee, Utensils, Pizza, 
  Beer, Wine, GlassWater, Apple, Banana, Carrot, Leaf, Flower2, TreeDeciduous, 
  Mountain, Waves, Flame, Snowflake, CloudLightning, Umbrella, Tent, Building, 
  Store, Factory, Warehouse, Landmark, School, Hospital, Hotel, Library, 
  Church, MapPin, Locate, Crosshair, Layers, 
  Grid, List, Table, BarChart, PieChart, LineChart, HeartPulse, 
  Stethoscope, Syringe, Pill, Microscope, FlaskConical, TestTube, Atom, 
  Dna, Brain, Eye, Ear, Hand, Footprints, Fingerprint, Scan, QrCode, 
  Barcode, Cpu, MemoryStick, Mouse, Keyboard, Monitor, Laptop, Tablet, 
  Smartphone, Watch, Headphones, Speaker, Tv, Radio, Battery, Plug, Wifi, 
  Bluetooth, Nfc, Usb, Server, Terminal, Code, Braces, Parentheses, Hash, 
  Percent, Minus, Equal, Divide, Infinity, Sigma, Pi, FunctionSquare, 
  Calculator, Pencil, Pen, Highlighter, Eraser, Brush, Palette, Scissors, 
  PenTool, Move, RotateCcw, RotateCw, Scale, Archive, Folder, File, Files, 
  Clipboard, StickyNote, Book, BookOpen, Gift, Send, Reply, Forward, 
  ExternalLink, RefreshCcw, RefreshCw, Repeat, Shuffle, Play, Pause, 
  Circle, Triangle, Hexagon, ThumbsUp, ThumbsDown, Smile, Frown, Meh, 
  Laugh, Angry, Annoyed, HelpCircle, Info, AlertCircle, AlertTriangle, 
  CheckCircle, XCircle, MoreHorizontal, MoreVertical, Menu, Layout, 
  Sidebar, PanelLeft, PanelRight, Maximize, Minimize, ZoomIn, ZoomOut, 
  SortAsc, SortDesc, ArrowUp, ArrowDown, ArrowLeft, ArrowRight, ChevronUp, 
  ChevronDown, ChevronRight, ChevronsUp, ChevronsDown, ChevronsLeft, 
  ChevronsRight, ArrowUpLeft, ArrowUpRight, ArrowDownLeft, ArrowDownRight, 
  MousePointer, Grab
} from 'lucide-react';

export const AVAILABLE_ICONS: Record<string, any> = {
  Ruler, Weight, Thermometer, Square, Box, Clock, Zap, HardDrive, Coins, 
  Activity, Wind, Droplets, Sun, Moon, Map, Navigation, Compass, Globe, 
  Search, Filter, Settings, Bell, Calendar, Camera, Image, Video, Music, 
  Mic, Phone, Mail, MessageSquare, Share2, Link, Download, Upload, Cloud, 
  Lock, Shield, Key, User, Heart, Star, Flag, Bookmark, Tag, ShoppingCart, 
  CreditCard, Wallet, Briefcase, GraduationCap, Trophy, Medal, Target, 
  Rocket, Plane, Car, Bike, Truck, Ship, Anchor, Coffee, Utensils, Pizza, 
  Beer, Wine, GlassWater, Apple, Banana, Carrot, Leaf, Flower2, TreeDeciduous, 
  Mountain, Waves, Flame, Snowflake, CloudLightning, Umbrella, Tent, Building, 
  Store, Factory, Warehouse, Landmark, School, Hospital, Hotel, Library, 
  Church, MapPin, Locate, Crosshair, Layers, 
  Grid, List, Table, BarChart, PieChart, LineChart, HeartPulse, 
  Stethoscope, Syringe, Pill, Microscope, FlaskConical, TestTube, Atom, 
  Dna, Brain, Eye, Ear, Hand, Footprints, Fingerprint, Scan, QrCode, 
  Barcode, Cpu, MemoryStick, Mouse, Keyboard, Monitor, Laptop, Tablet, 
  Smartphone, Watch, Headphones, Speaker, Tv, Radio, Battery, Plug, Wifi, 
  Bluetooth, Nfc, Usb, Server, Terminal, Code, Braces, Parentheses, Hash, 
  Percent, Minus, Equal, Divide, Infinity, Sigma, Pi, FunctionSquare, 
  Calculator, Pencil, Pen, Highlighter, Eraser, Brush, Palette, Scissors, 
  PenTool, Move, RotateCcw, RotateCw, Scale, Archive, Folder, File, Files, 
  Clipboard, StickyNote, Book, BookOpen, Gift, Send, Reply, Forward, 
  ExternalLink, RefreshCcw, RefreshCw, Repeat, Shuffle, Play, Pause, 
  Circle, Triangle, Hexagon, ThumbsUp, ThumbsDown, Smile, Frown, Meh, 
  Laugh, Angry, Annoyed, HelpCircle, Info, AlertCircle, AlertTriangle, 
  CheckCircle, XCircle, MoreHorizontal, MoreVertical, Menu, Layout, 
  Sidebar, PanelLeft, PanelRight, Maximize, Minimize, ZoomIn, ZoomOut, 
  SortAsc, SortDesc, ArrowUp, ArrowDown, ArrowLeft, ArrowRight, ChevronUp, 
  ChevronDown, ChevronRight, ChevronsUp, ChevronsDown, ChevronsLeft, 
  ChevronsRight, ArrowUpLeft, ArrowUpRight, ArrowDownLeft, ArrowDownRight, 
  MousePointer, Grab
};
